#' Run soNNia Selection Analysis
#'
#' @description Infer selection pressures on TCRs using soNNia. Requires a
#'   background dataset of unselected sequences (generated by OLGA).
#'
#' @param input A Seurat or SingleCellExperiment object containing scRepertoire TCR data.
#' @param chains Which chain to analyze: "TRB" or "TRA". Default is "TRB".
#' @param background_file Path to CSV file with background sequences (from generateOLGA).
#' @param organism Organism: "human" or "mouse". Default is "human".
#' @param save_folder Directory to save soNNia model. Default is "sonia_output".
#' @param n_epochs Number of training epochs. Default is 100.
#' @param return_object If TRUE, adds selection scores to metadata. Default is TRUE.
#'
#' @details
#' This function requires a background dataset of unselected TCR sequences, which
#' can be generated using generateOLGA(). The selected sequences are extracted from
#' the input object and compared to this background to infer selection pressures.
#'
#' @return If return_object=TRUE, returns input object with selection scores in
#'   metadata. Otherwise returns the soNNia results.
#'
#' @export
#' @importFrom immApex getIR
#' @importFrom methods is
#' @importFrom utils write.csv
#'
#' @examples
#' data(immLynx_example)
#' \donttest{
#'   # Step 1: Generate background sequences with OLGA
#'   background <- generateOLGA(n = 1000, model = "humanTRB")
#'   bg_file <- tempfile(fileext = ".csv")
#'   utils::write.csv(background, bg_file, row.names = FALSE)
#'
#'   # Step 2: Run soNNia selection analysis
#'   seurat_obj <- runSoNNia(immLynx_example,
#'                           chains = "TRB",
#'                           background_file = bg_file)
#'
#'   # Get raw results instead of adding to object
#'   sonia_results <- runSoNNia(immLynx_example,
#'                              chains = "TRB",
#'                              background_file = bg_file,
#'                              return_object = FALSE)
#' }
runSoNNia <- function(input,
                     chains = c("TRB", "TRA"),
                     background_file,
                     organism = "human",
                     save_folder = "sonia_output",
                     n_epochs = 100,
                     return_object = TRUE) {

  chains <- match.arg(chains)

  # Determine input type
  .is_sce <- methods::is(input, "SingleCellExperiment")
  .is_seurat <- methods::is(input, "Seurat")

  if (!.is_sce && !.is_seurat) {
    stop("Input must be a Seurat or SingleCellExperiment object")
  }

  if (!file.exists(background_file)) {
    stop("Background file not found: ", background_file)
  }

  message("Extracting ", chains, " sequences from object...")
  tcr_data <- immApex::getIR(input, chains = chains)
  tcr_data <- tcr_data[!is.na(tcr_data$cdr3_aa), ]

  if (nrow(tcr_data) == 0) {
    stop("No valid ", chains, " sequences found.")
  }

  # Create data directory
  data_dir <- file.path(save_folder, "data")
  if (!dir.exists(data_dir)) {
    dir.create(data_dir, recursive = TRUE)
  }

  message("Preparing data for soNNia...")

  # Format selected sequences for soNNia
  col_suffix <- if (chains == "TRB") "_b" else "_a"

  # Build the data.frame with required columns
  selected_data <- list()
  selected_data[[paste0("cdr3", col_suffix, "_aa")]] <- tcr_data$cdr3_aa

  if (!all(is.na(tcr_data$v))) {
    selected_data[[paste0("v", col_suffix, "_gene")]] <- tcr_data$v
  }
  if (!all(is.na(tcr_data$j))) {
    selected_data[[paste0("j", col_suffix, "_gene")]] <- tcr_data$j
  }

  selected_df <- as.data.frame(selected_data, stringsAsFactors = FALSE)

  # Save selected data
  selected_file <- file.path(data_dir, "selected_tcrs.csv")
  write.csv(selected_df, selected_file, row.names = FALSE)

  # Copy background file to data directory
  file.copy(background_file, file.path(data_dir, basename(background_file)))

  message("Running soNNia selection analysis...")

  # Run soNNia
  results <- calculate.sonia(
    data_folder = data_dir,
    data_filename = "selected_tcrs.csv",
    pgen_filename = basename(background_file),
    organism = organism,
    dataset_type = "TCR",
    n_epochs = n_epochs,
    save_folder = save_folder
  )

  # Extract selection scores (implementation depends on soNNia output format)
  # This is a placeholder - adjust based on actual soNNia output

  if (return_object) {
    message("Adding selection scores to metadata...")

    # Add selection information to metadata
    # (Implementation depends on soNNia output structure)

    message("soNNia results added to object")
    return(input)

  } else {
    return(results)
  }
}
