#' Run soNNia Selection Analysis
#'
#' @description Infer selection pressures on TCRs using soNNia. Requires a
#'   background dataset of unselected sequences (generated by OLGA).
#'
#' @param seurat_obj A Seurat object containing scRepertoire TCR data
#' @param chains Which chain to analyze: "TRB" or "TRA". Default is "TRB".
#' @param background_file Path to CSV file with background sequences (from generateOLGA)
#' @param organism Organism: "human" or "mouse". Default is "human".
#' @param save_folder Directory to save soNNia model. Default is "sonia_output".
#' @param n_epochs Number of training epochs. Default is 100.
#' @param return_seurat If TRUE, adds selection scores to metadata. Default is TRUE.
#'
#' @details
#' This function requires a background dataset of unselected TCR sequences, which
#' can be generated using generateOLGA(). The selected sequences are extracted from
#' the Seurat object and compared to this background to infer selection pressures.
#'
#' @return If return_seurat=TRUE, returns Seurat object with selection scores in
#'   metadata. Otherwise returns the soNNia results.
#'
#' @export
#' @importFrom immApex getIR
#'
#' @examples
#' \dontrun{
#'   # Generate background
#'   background <- generateOLGA(n = 10000, model = "humanTRB")
#'   write.csv(background, "background.csv", row.names = FALSE)
#'
#'   # Run soNNia
#'   seurat_obj <- runSonia(seurat_obj,
#'                          chains = "TRB",
#'                          background_file = "background.csv")
#' }
runSoNNia <- function(seurat_obj,
                     chains = c("TRB", "TRA"),
                     background_file,
                     organism = "human",
                     save_folder = "sonia_output",
                     n_epochs = 100,
                     return_seurat = TRUE) {
  
  chains <- match.arg(chains)
  
  if (!file.exists(background_file)) {
    stop("Background file not found: ", background_file)
  }
  
  message("Extracting ", chains, " sequences from Seurat object...")
  tcr_data <- immApex::getIR(seurat_obj, chains = chains)
  tcr_data <- tcr_data[!is.na(tcr_data$cdr3_aa), ]
  
  if (nrow(tcr_data) == 0) {
    stop("No valid ", chains, " sequences found.")
  }
  
  # Create data directory
  data_dir <- file.path(save_folder, "data")
  if (!dir.exists(data_dir)) {
    dir.create(data_dir, recursive = TRUE)
  }
  
  message("Preparing data for soNNia...")
  
  # Format selected sequences
  col_suffix <- ifelse(chains == "TRB", "_b", "_a")
  
  selected_df <- data.frame(
    stringsAsFactors = FALSE
  )
  selected_df[[paste0("cdr3", col_suffix, "_aa")]] <- tcr_data$cdr3_aa
  
  if (!all(is.na(tcr_data$v))) {
    selected_df[[paste0("v", col_suffix, "_gene")]] <- tcr_data$v
  }
  if (!all(is.na(tcr_data$j))) {
    selected_df[[paste0("j", col_suffix, "_gene")]] <- tcr_data$j
  }
  
  # Save selected data
  selected_file <- file.path(data_dir, "selected_tcrs.csv")
  write.csv(selected_df, selected_file, row.names = FALSE)
  
  # Copy background file to data directory
  file.copy(background_file, file.path(data_dir, basename(background_file)))
  
  message("Running soNNia selection analysis...")
  
  # Run soNNia
  results <- calculate.sonia(
    data_folder = data_dir,
    data_filename = "selected_tcrs.csv",
    pgen_filename = basename(background_file),
    organism = organism,
    dataset_type = "TCR",
    n_epochs = n_epochs,
    save_folder = save_folder
  )
  
  # Extract selection scores (implementation depends on soNNia output format)
  # This is a placeholder - adjust based on actual soNNia output
  
  if (return_seurat) {
    message("Adding selection scores to metadata...")
    
    # Add selection information to metadata
    # (Implementation depends on soNNia output structure)
    
    message("soNNia results added to Seurat object")
    return(seurat_obj)
    
  } else {
    return(results)
  }
}
